push:
  branches:
    - workspace
name: Continuous deployment
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Commit report
        run: |
          git config --global user.name 'Monkey'
          git config --global user.email 'monkey@domonda.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Set up node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
      - name: Bump version
        run: yarn bumpver --yes
