name: Publish

on:
  repository_dispatch:
    types: [publish]

jobs:
  release-and-publish:
    name: Release and publish
    runs-on: ubuntu-latest
    if: github.actor == 'domondabot'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'
      - name: Configure git user
        run: |
          git config --global user.name 'domondabot'
          git config --global user.email 'bot@domonda.com'
      - name: Build
        run: yarn build
      # - name: Release
      #   env:
      #     GH_TOKEN: ${{ secrets.BOT_PAT }}
      #   run: yarn release --create-release github --yes
      # - name: Publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: yarn publish --yes
