on:
  push:
    tags:
      - '*'

name: Publish
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure git
        run: |
          git config --global user.name 'domondabot'
          git config --global user.email 'bot@domonda.com'
          git remote set-url origin https://x-access-token:${{ secrets.BOT_PAT }}@github.com/$GITHUB_REPOSITORY
      - name: Set up node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        run: yarn
      - name: Publish
        run: echo :)
        # run: yarn publish
