on:
  push:
    branches:
      - workspace

name: Release
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '12'
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-
      - name: Install
        run: yarn install --immutable
      - name: Lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '12'
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-
      - name: Install
        run: yarn install --immutable
      - name: Test
        run: yarn test

  type-check:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '12'
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-
      - name: Install
        run: yarn install --immutable
      - name: Check
        run: yarn type-check

  version:
    name: Version
    needs: [lint, test, type-check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure git
        run: |
          git config --global user.name 'domondabot'
          git config --global user.email 'bot@domonda.com'
          git remote set-url origin https://x-access-token:${{ secrets.BOT_PAT }}@github.com/$GITHUB_REPOSITORY
      - name: Set up node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '12'
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-
      - name: Install
        run: yarn install --immutable
      - name: Version
        run: yarn version
